export interface BiqTokenPayload {
  sub: string;
  client: string;

}

/**
 * We have 2 tokens:
 * - App token that is generated by Firebase
 *  - used to interact with [APP-BACKEND]
 * - Protocol token that is generated by us
 *  - used to interact with [BACKEND]
 * 
 * Where should we include organizer access, if at all ?
 * Or just maybe include that user has organizer access (true/false).
 * A user can belong to multiple organizers so the list can grow large and exceed token size limits.
 */